<p>In page help is indicated by the <span class="info" title="Tooltip Help">&nbsp;</span> icon or a blue border around an entry field.</p>

<ol>
	<li>Visit 'Settings->RSSInjection->Settings' in your admin panel.</li>
	<li>Configure the header and footer you wish to be displayed on all your posts in your RSS feed.</li>
	<li>Click Apply.</li>
	<li>If you want the changes to be imediate you must clear the cache WordPress has of the RSS feed, to do this choose any post and update.</li>
</ol>