<?php echo $this->options['name']; ?> allows you to modify the post for your RSS feed.
You may be able think of you own reasons for doing this, but it was originally designed to add a copyright message and link to the feed to show the posts origins should a blog scraper republish your feed on their own blog.   
Another possible use is to add extra content to your feed to entice users to subscribe, which this is mind you can now add a message that will only display in the blog to promote this offer.
 
